services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client
      - "9363:9363" # Prometheus
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse          # Persistent data storage
      - ./clickhouse.xml:/etc/clickhouse-server/config.d/custom-clickhouse.xml:ro  # Optional custom configuration
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Web interface
    volumes:
      - ./prometheus_data:/prometheus                 # Persistent data storage
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro  # Prometheus config from local disk
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml" # Ensure correct path to config
      - "--storage.tsdb.retention.time=1ms"
    restart: unless-stopped