# Sources
#[sources.host_metrics]
#type = "host_metrics"
#scrape_interval_secs = "10s"  # Collect metrics every 30 seconds
#metrics = [
#  "cpu",           # CPU usage
#  "disk",          # Disk metrics
#  "memory",        # Memory usage
#  "network",       # Network stats
#  "load",          # Load average
#]

[sources.internal_metrics]
type = "internal_metrics"
scrape_interval_secs = 5
# Collect internal Vector metrics every 30 seconds

# Transforms
#[transforms.host_metrics_to_prometheus]
#type = "remap"  # Apply transformation to the host_metrics
#inputs = ["host_metrics"]
#source = '''
#  .host_metrics = {
#    "cpu": .cpu,
#    "memory": .memory,
#    "disk": .disk,
#    "network": .network,
#    "load": .load
#  }
#  .timestamp = now()
#'''

[transforms.internal_metrics_to_prometheus]
type = "remap"  # Apply transformation to the internal_metrics
inputs = ["internal_metrics"]
source = '''
  .internal_metrics = {
    "vector_version": .vector_version,
    "vector_uptime": .uptime
  }
  .timestamp = now()
'''

# Sinks
[sinks.metrics_prometheus]
type = "prometheus_remote_write"
inputs = ["internal_metrics"]
endpoint = "http://host.docker.internal:8080/api/v1/write"
#compression = "gzip"  # Optionally, use gzip for compression